import 'dart:convert';
import 'dart:typed_data';
import 'package:excel/excel.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:xml/xml.dart';
import '../../core/models.dart';

class ImportDataScreen extends StatefulWidget {
  const ImportDataScreen({super.key,required this.snapshot,required this.onImportTransactions,required this.onRefresh});
  final FinancialSnapshot snapshot;
  final Future<void> Function(List<FinancialTransaction>) onImportTransactions;
  final Future<void> Function() onRefresh;
  @override State<ImportDataScreen> createState()=>_ImportDataScreenState();
}

class _ImportDataScreenState extends State<ImportDataScreen>{
  String? fileName,error; bool busy=false; List<Map<String,String>> rows=[]; List<String> columns=[];
  final fields=const {'date':'Data','description':'Descrição','amount':'Valor','type':'Entrada/Saída','category':'Categoria','account':'Conta/Banco','card':'Cartão','source':'Origem'};
  final Map<String,String?> mapping={}; int? fallbackAccountId;

  String _norm(String s)=>s.toLowerCase().replaceAll(RegExp(r'[^a-z0-9áàãâéêíóôõúç]'),'');
  String? _guess(String field){
    final aliases=<String,List<String>>{
      'date':['data','date','dtmov','datamovimento','datetime'], 'description':['descricao','descrição','historico','histórico','memo','description','detalhe'],
      'amount':['valor','amount','vltransacao','vlmovimento','value'], 'type':['tipo','type','natureza','entrada/saida','entrada/saída','transactiontype'],
      'category':['categoria','category'], 'account':['conta','banco','account','bank'], 'card':['cartao','cartão','card','creditcard'], 'source':['origem','source']};
    for(final c in columns){final n=_norm(c);if(aliases[field]!.any((a)=>n==_norm(a)||n.contains(_norm(a))))return c;}return null;
  }
  void _autoMap(){for(final f in fields.keys){mapping[f]=_guess(f);}}

  List<List<String>> _delimited(String text){
    final lines=const LineSplitter().convert(text).where((e)=>e.trim().isNotEmpty).toList(); if(lines.isEmpty)return [];
    final sample=lines.first; final sep=[',',';','\t','|'].reduce((a,b)=>sample.split(a).length>=sample.split(b).length?a:b);
    return lines.map((line){final out=<String>[];var cur='';var quoted=false;for(var i=0;i<line.length;i++){final ch=line[i];if(ch=='"'){if(quoted&&i+1<line.length&&line[i+1]=='"'){cur+='"';i++;}else{quoted=!quoted;}}else if(ch==sep&&!quoted){out.add(cur.trim());cur='';}else{cur+=ch;}}out.add(cur.trim());return out;}).toList();
  }
  List<Map<String,String>> _table(List<List<String>> table){if(table.length<2)return [];final h=table.first.map((e)=>e.trim().isEmpty?'Coluna':e.trim()).toList();return table.skip(1).map((r)=><String,String>{for(var i=0;i<h.length;i++)h[i]:i<r.length?r[i].trim():''}).toList();}
  List<Map<String,String>> _jsonRows(String text){final raw=jsonDecode(text);final list=raw is List?raw:(raw is Map?(raw['transactions']??raw['transacoes']??raw['data']??[raw]):[]);if(list is! List)return [];return list.whereType<Map>().map((e)=>e.map((k,v)=>MapEntry(k.toString(),v?.toString()??''))).toList();}
  List<Map<String,String>> _xmlRows(String text){final doc=XmlDocument.parse(text);var nodes=doc.descendants.whereType<XmlElement>().where((e)=>['transaction','transacao','movimento','item','record'].contains(e.name.local.toLowerCase())).toList();if(nodes.isEmpty&&doc.rootElement.children.whereType<XmlElement>().isNotEmpty)nodes=doc.rootElement.children.whereType<XmlElement>().toList();return nodes.map((e)=><String,String>{for(final c in e.children.whereType<XmlElement>())c.name.local:c.innerText.trim(),for(final a in e.attributes)a.name.local:a.value}).where((e)=>e.isNotEmpty).toList();}
  Future<void> _pick() async{
    setState(()=>error=null);final result=await FilePicker.platform.pickFiles(type:FileType.custom,allowedExtensions:['xlsx','csv','json','txt','xml'],withData:true);if(result==null)return;final f=result.files.single;final bytes=f.bytes;if(bytes==null){setState(()=>error='Não foi possível ler o arquivo.');return;}
    try{List<Map<String,String>> parsed=[];final ext=(f.extension??'').toLowerCase();if(ext=='xlsx'){final book=Excel.decodeBytes(bytes);if(book.tables.isNotEmpty){final sheet=book.tables.values.first;parsed=_table(sheet.rows.map((r)=>r.map((c)=>c?.value?.toString()??'').toList()).toList());}}else{final text=utf8.decode(bytes,allowMalformed:true);if(ext=='json')parsed=_jsonRows(text);else if(ext=='xml')parsed=_xmlRows(text);else parsed=_table(_delimited(text));}
      if(parsed.isEmpty)throw Exception('Nenhum registro foi encontrado.');final cols=<String>{};for(final r in parsed.take(100)){cols.addAll(r.keys);}setState((){fileName=f.name;rows=parsed;columns=cols.toList();_autoMap();});
    }catch(e){setState(()=>error='Não foi possível analisar o arquivo: ${e.toString().replaceFirst('Exception: ','')}');}
  }
  String? _v(Map<String,String> r,String f){final c=mapping[f];return c==null?null:r[c]?.trim();}
  double? _money(String? raw){if(raw==null||raw.trim().isEmpty)return null;var s=raw.replaceAll(RegExp(r'[^0-9,.-]'),'');if(s.contains(',')&&s.contains('.')){if(s.lastIndexOf(',')>s.lastIndexOf('.'))s=s.replaceAll('.','').replaceAll(',','.');else s=s.replaceAll(',','');}else if(s.contains(',')){s=s.replaceAll('.','').replaceAll(',','.');}return double.tryParse(s);}
  String? _date(String? raw){if(raw==null||raw.trim().isEmpty)return null;final s=raw.trim();final iso=DateTime.tryParse(s);if(iso!=null)return '${iso.year.toString().padLeft(4,'0')}-${iso.month.toString().padLeft(2,'0')}-${iso.day.toString().padLeft(2,'0')}';final m=RegExp(r'^(\d{1,2})[/-](\d{1,2})[/-](\d{2,4})').firstMatch(s);if(m!=null){var y=int.parse(m[3]!);if(y<100)y+=2000;return '${y.toString().padLeft(4,'0')}-${m[2]!.padLeft(2,'0')}-${m[1]!.padLeft(2,'0')}';}return null;}
  String _type(String? raw,double amount){var n=(raw??'').trim().toLowerCase();const accents={'á':'a','à':'a','ã':'a','â':'a','ä':'a','é':'e','è':'e','ê':'e','ë':'e','í':'i','ì':'i','î':'i','ï':'i','ó':'o','ò':'o','õ':'o','ô':'o','ö':'o','ú':'u','ù':'u','û':'u','ü':'u','ç':'c'};accents.forEach((a,b)=>n=n.replaceAll(a,b));n=n.replaceAll(RegExp(r'[^a-z0-9]'),'');if(n.contains('entrada')||n.contains('receita')||n.contains('income')||n.contains('credit')||n.contains('credito'))return 'income';if(n.contains('saida')||n.contains('despesa')||n.contains('expense')||n.contains('debit')||n.contains('debito'))return 'expense';return amount<0?'expense':'income';}
  FinancialAccount? _account(String? raw){if(raw!=null&&raw.isNotEmpty){final n=_norm(raw);for(final a in widget.snapshot.accounts){if(_norm(a.institutionName).contains(n)||n.contains(_norm(a.institutionName))||_norm(a.accountName??'')==n)return a;}}if(fallbackAccountId!=null){for(final a in widget.snapshot.accounts){if(a.id==fallbackAccountId)return a;}}return null;}
  FinanceCategory? _category(String? raw){if(raw==null)return null;final n=_norm(raw);for(final c in widget.snapshot.categories){if(_norm(c.name)==n)return c;}return null;}
  CreditCardInfo? _card(String? raw){if(raw==null||raw.isEmpty)return null;final n=_norm(raw);for(final c in widget.snapshot.cards){if(n.contains(_norm(c.lastFour))||n.contains(_norm(c.nickname??''))||n.contains(_norm(c.bankName)))return c;}return null;}
  List<FinancialTransaction> _valid(){final out=<FinancialTransaction>[];var seed=DateTime.now().microsecondsSinceEpoch;for(final r in rows){final amount=_money(_v(r,'amount'));final date=_date(_v(r,'date'));if(amount==null||date==null||amount==0)continue;final card=_card(_v(r,'card'));final account=_account(_v(r,'account'));final desc=_v(r,'description');out.add(FinancialTransaction(id:seed++,date:date,description:(desc==null||desc.isEmpty)?'Importação de arquivo':desc,amount:amount.abs(),type:card!=null?'expense':_type(_v(r,'type'),amount),accountId:account?.id,categoryId:_category(_v(r,'category'))?.id,importCategoryName:_v(r,'category'),cardId:card?.id,source:(_v(r,'source')?.toLowerCase().contains('open')??false)?'open_finance':'manual'));}return out;}
  String _sig(FinancialTransaction t)=>'${t.date}|${_norm(t.description)}|${t.amount.toStringAsFixed(2)}|${t.type}|${t.accountId}|${t.cardId}';
  Future<void> _import() async{final valid=_valid();final existing=widget.snapshot.transactions.map(_sig).toSet();final unique=<FinancialTransaction>[];final seen=<String>{...existing};for(final t in valid){if(seen.add(_sig(t)))unique.add(t);}if(unique.isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Nenhuma transação nova para importar.')));return;}final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Confirmar importação'),content:Text('${unique.length} transação(ões) serão importadas. ${valid.length-unique.length} possível(is) duplicada(s) serão ignoradas.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Importar'))]))??false;if(!ok)return;setState(()=>busy=true);var done=0;try{await widget.onImportTransactions(unique);done=unique.length;await widget.onRefresh();if(mounted){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$done transação(ões) importada(s) com sucesso.')));Navigator.pop(context,true);}}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Importados $done de ${unique.length}. Erro: ${e.toString().replaceFirst('Exception: ','')}')));}finally{if(mounted)setState(()=>busy=false);}}
  @override Widget build(BuildContext context){final valid=_valid();final existing=widget.snapshot.transactions.map(_sig).toSet();final duplicates=valid.where((t)=>existing.contains(_sig(t))).length;return Scaffold(appBar:AppBar(title:const Text('Importar dados financeiros')),body:ListView(padding:const EdgeInsets.all(16),children:[
    Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Importe suas movimentações',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:6),const Text('Formatos aceitos: Excel (.xlsx), CSV, JSON, TXT e XML. Nada é gravado antes da sua confirmação.'),const SizedBox(height:14),FilledButton.icon(onPressed:busy?null:_pick,icon:const Icon(Icons.upload_file),label:Text(fileName==null?'Selecionar arquivo':'Trocar arquivo')),if(fileName!=null)Padding(padding:const EdgeInsets.only(top:8),child:Text(fileName!)),if(error!=null)Padding(padding:const EdgeInsets.only(top:8),child:Text(error!,style:TextStyle(color:Theme.of(context).colorScheme.error)))]))),
    if(rows.isNotEmpty)...[const SizedBox(height:12),Text('Mapear campos',style:Theme.of(context).textTheme.titleLarge),const Text('Confira quais colunas do arquivo correspondem aos campos do FinanceApp.'),const SizedBox(height:8),...fields.entries.map((e)=>Padding(padding:const EdgeInsets.only(bottom:8),child:DropdownButtonFormField<String>(value:mapping[e.key],decoration:InputDecoration(labelText:e.value),items:[const DropdownMenuItem<String>(value:null,child:Text('Não importar')), ...columns.map((c)=>DropdownMenuItem(value:c,child:Text(c,overflow:TextOverflow.ellipsis)))],onChanged:(v)=>setState(()=>mapping[e.key]=v)))),if(widget.snapshot.accounts.isNotEmpty)DropdownButtonFormField<int>(value:fallbackAccountId,decoration:const InputDecoration(labelText:'Conta padrão (quando o arquivo não informar)'),items:[const DropdownMenuItem<int>(value:null,child:Text('Nenhuma')), ...widget.snapshot.accounts.map((a)=>DropdownMenuItem(value:a.id,child:Text(a.institutionName)))],onChanged:(v)=>setState(()=>fallbackAccountId=v)),
      const SizedBox(height:16),Wrap(spacing:8,runSpacing:8,children:[Chip(label:Text('${rows.length} linhas')),Chip(label:Text('${valid.length} válidas')),Chip(label:Text('$duplicates possíveis duplicadas')),Chip(label:Text('${rows.length-valid.length} com dados insuficientes'))]),const SizedBox(height:12),Text('Pré-visualização',style:Theme.of(context).textTheme.titleLarge),...valid.take(8).map((t)=>Card(child:ListTile(title:Text(t.description),subtitle:Text('${t.date} • ${t.type=='income'?'Entrada':'Saída'}${t.cardId!=null?' • Cartão':''}'),trailing:Text('R\$ ${t.amount.toStringAsFixed(2).replaceAll('.',',')}')))),if(valid.length>8)Text('... e mais ${valid.length-8} registro(s).'),const SizedBox(height:16),FilledButton.icon(onPressed:busy||mapping['date']==null||mapping['amount']==null?null:_import,icon:busy?const SizedBox.square(dimension:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.file_download_done),label:Text(busy?'Importando...':'Revisar e importar'))]
  ]));}
}
