name: financeapp_multiplatform
description: FinanceApp multiplataforma - Android, iOS e Web.
publish_to: "none"
version: 4.0.0+40000

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  http_parser: ^4.1.0
  shared_preferences: ^2.3.2
  google_sign_in: ^6.2.2
  url_launcher: ^6.3.1
  pdf: ^3.11.1
  printing: ^5.13.4
  image_picker: ^1.1.2
  mobile_scanner: ^6.0.11
  file_picker: ^8.1.2
  excel: ^4.0.6
  xml: ^6.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/financeapp_logo.png
