import 'package:shared_preferences/shared_preferences.dart';

class AppCustomization {
  const AppCustomization({
    this.showDashboardTab=true,this.showTransactionsTab=true,this.showForecastTab=true,this.showIntelligenceTab=true,this.showAccountsTab=true,
    this.showCurrentBalance=true,this.showIncome=true,this.showExpenses=true,this.showCardPurchases=true,this.showQuickActions=true,
    this.showRecentTransactions=true,this.showMonthlyBudgets=true,this.showBiggestExpense=true,this.showInvoices=true,this.compactDashboard=false,
  });
  final bool showDashboardTab,showTransactionsTab,showForecastTab,showIntelligenceTab,showAccountsTab;
  final bool showCurrentBalance,showIncome,showExpenses,showCardPurchases,showQuickActions,showRecentTransactions,showMonthlyBudgets,showBiggestExpense,showInvoices,compactDashboard;
  AppCustomization copyWith({bool? showDashboardTab,bool? showTransactionsTab,bool? showForecastTab,bool? showIntelligenceTab,bool? showAccountsTab,bool? showCurrentBalance,bool? showIncome,bool? showExpenses,bool? showCardPurchases,bool? showQuickActions,bool? showRecentTransactions,bool? showMonthlyBudgets,bool? showBiggestExpense,bool? showInvoices,bool? compactDashboard})=>AppCustomization(
    showDashboardTab:showDashboardTab??this.showDashboardTab,showTransactionsTab:showTransactionsTab??this.showTransactionsTab,showForecastTab:showForecastTab??this.showForecastTab,showIntelligenceTab:showIntelligenceTab??this.showIntelligenceTab,showAccountsTab:showAccountsTab??this.showAccountsTab,
    showCurrentBalance:showCurrentBalance??this.showCurrentBalance,showIncome:showIncome??this.showIncome,showExpenses:showExpenses??this.showExpenses,showCardPurchases:showCardPurchases??this.showCardPurchases,showQuickActions:showQuickActions??this.showQuickActions,showRecentTransactions:showRecentTransactions??this.showRecentTransactions,showMonthlyBudgets:showMonthlyBudgets??this.showMonthlyBudgets,showBiggestExpense:showBiggestExpense??this.showBiggestExpense,showInvoices:showInvoices??this.showInvoices,compactDashboard:compactDashboard??this.compactDashboard);
}
class AppCustomizationStore {
  static const _prefix='financeapp_flutter_customization_v3_'; String _key(String u,String n)=>'$_prefix${u}_$n';
  Future<AppCustomization> read(String u)async{final p=await SharedPreferences.getInstance();bool b(String n,bool d)=>p.getBool(_key(u,n))??d;return AppCustomization(showDashboardTab:b('dashboard_tab',true),showTransactionsTab:b('transactions_tab',true),showForecastTab:b('forecast_tab',true),showIntelligenceTab:b('intelligence_tab',true),showAccountsTab:b('accounts_tab',true),showCurrentBalance:b('current_balance',true),showIncome:b('income',true),showExpenses:b('expenses',true),showCardPurchases:b('card_purchases',true),showQuickActions:b('quick_actions',true),showRecentTransactions:b('recent_transactions',true),showMonthlyBudgets:b('monthly_budgets',true),showBiggestExpense:b('biggest_expense',true),showInvoices:b('invoices',true),compactDashboard:b('compact_dashboard',false));}
  Future<void> save(String u,AppCustomization v)async{final p=await SharedPreferences.getInstance();await Future.wait([p.setBool(_key(u,'dashboard_tab'),v.showDashboardTab),p.setBool(_key(u,'transactions_tab'),v.showTransactionsTab),p.setBool(_key(u,'forecast_tab'),v.showForecastTab),p.setBool(_key(u,'intelligence_tab'),v.showIntelligenceTab),p.setBool(_key(u,'accounts_tab'),v.showAccountsTab),p.setBool(_key(u,'current_balance'),v.showCurrentBalance),p.setBool(_key(u,'income'),v.showIncome),p.setBool(_key(u,'expenses'),v.showExpenses),p.setBool(_key(u,'card_purchases'),v.showCardPurchases),p.setBool(_key(u,'quick_actions'),v.showQuickActions),p.setBool(_key(u,'recent_transactions'),v.showRecentTransactions),p.setBool(_key(u,'monthly_budgets'),v.showMonthlyBudgets),p.setBool(_key(u,'biggest_expense'),v.showBiggestExpense),p.setBool(_key(u,'invoices'),v.showInvoices),p.setBool(_key(u,'compact_dashboard'),v.compactDashboard)]);}
}
